import { readFile } from "node:fs/promises";
import path from "node:path";
import OpenAI from "openai";
import type { ChatCompletionCreateParamsNonStreaming } from "openai/resources/chat/completions";
import { openaiAdapter } from "promptopskit/openai";
import { PromptOpsKitDemo } from "@/app/promptopskit-demo";

async function loadPromptMarkdownSource(): Promise<string> {
  return readFile(path.join(process.cwd(), "prompts", "summarizePullRequest.md"), "utf8");
}

export default async function Home() {
  const promptMarkdownSource = await loadPromptMarkdownSource();

  async function summarizePullRequestAction(
    environment: string,
    pullRequestBody: string,
  ): Promise<{ model: string; requestBodyPreview: string; summary: string }> {
    "use server";

    // 1 - render the prompt and resolve environment and variables into a request body
    const request = await openaiAdapter.renderPrompt(
      {
        path: "summarizePullRequest",
      },
      {
        environment,
        variables: {
          pull_request_body: pullRequestBody,
        },
        strict: true,
      },
    );

    // special case, if the prompt rendering returns a "returnMessage", we can short-circuit and return that directly without making an OpenAI API call
    if ("returnMessage" in request) {
      return {
        model: "validation",
        requestBodyPreview: "short-circuit",
        summary: request.returnMessage,
      };
    }

    // 2 - make the OpenAI API call with the rendered request body
    const openAi = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
    const completion = await openAi.chat.completions.create(
      request.body as unknown as ChatCompletionCreateParamsNonStreaming,
    );

    // for this example, we return the model used, a preview of the request body, and the summary generated by the model (which we assume is in the first choice's message content)
    return {
      model: completion.model,
      requestBodyPreview: JSON.stringify(request.body, null, 2),
      summary: completion.choices[0]?.message?.content?.trim() ?? "",
    };
  }

  return (
    <PromptOpsKitDemo
      promptMarkdownSource={promptMarkdownSource}
      summarizePullRequestAction={summarizePullRequestAction}
    />
  );
}